local colors = require('yello_world.palette')

local highlights = {}

highlights.groups = {
  Cursor = { fg = colors.bg, bg = colors.yellow },
  lCursor = { fg = colors.bg, bg = colors.yellow },
  CursorIM = { fg = colors.bg, bg = colors.yellow },
  CursorColumn = { fg = colors.fg, bg = colors.bg_alt },
  CursorLine = { bg = colors.bg_alt },
  Directory = { fg = colors.fg, bg = colors.bg },
  DiffAdd = { fg = colors.green, bg = colors.bg },
  DiffChange = { fg = colors.warning, bg = colors.bg },
  DiffDelete = { fg = colors.error, bg = colors.bg },
  DiffText = { fg = colors.green, bg = colors.bg },
  EndOfBuffer = { fg = colors.gray, bg = colors.bg },
  TermCursor = { fg = colors.bg, bg = colors.yellow },
  TermCursorNC = { fg = colors.bg, bg = colors.bg_alt },
  ErrorMsg = { fg = colors.error },
  WinSeparator = { fg = colors.gray, bg = colors.bg },
  Folded = { fg = colors.green },
  SignColumn = { bg = colors.bg },
  IncSearch = { fg = colors.bg, bg = colors.yellow },
  Substitute = { fg = colors.bg, bg = colors.yellow },
  LineNr = { fg = colors.fg },
  LineNrAbove = { fg = colors.gray },
  LineNrBelow = { fg = colors.gray },
  CursorLineNr = { bg = colors.bg_alt },
  CursorLineSign = { bg = colors.bg },
  MatchParen = { fg = colors.yellow },
  ModeMsg = { fg = colors.fg, bg = colors.bg },
  MsgArea = { fg = colors.fg, bg = colors.bg },
  MsgSeparator = { fg = colors.white, bg = colors.bg },
  MoreMsg = { fg = colors.fg, bg = colors.bg },
  NonText = { fg = colors.fg, bg = colors.bg },
  Normal = { fg = colors.fg, bg = colors.bg },
  NormalFloat = { link = 'Normal' },
  NormalNC = { link = 'Normal' },
  Pmenu = { fg = colors.bg, bg = colors.white },
  PmenuSel = { fg = colors.bg, bg = colors.yellow },
  PmenuSbar = { bg = colors.bg_alt },
  PmenuThumb = { bg = colors.white },
  Question = { fg = colors.warning },
  Search = { fg = colors.bg, bg = colors.yellow },
  SpecialKey = { fg = colors.gray, bg = colors.bg },
  SpellBad = { fg = colors.error, bg = colors.bg, undercurl = true },
  SpellCap = { fg = colors.warning, bg = colors.bg, undercurl = true },
  SpellLocal = { fg = colors.warning, bg = colors.bg, undercurl = true },
  SpellRare = { fg = colors.warning, bg = colors.bg, undercurl = true },
  StatusLine = { fg = colors.fg, bg = colors.bg },
  StatusLineNC = { fg = colors.gray, bg = colors.bg },
  Tabline = { bg = colors.bg },
  TablineFill = { bg = colors.bg },
  TablineSel = { fg = colors.fg, bg = colors.bg },
  Title = { fg = colors.yellow },
  Visual = { bg = colors.bg_alt },
  VisualNOS = { bg = colors.bg_alt },
  WarningMsg = { fg = colors.warning },
  Whitespace = { fg = colors.gray },
  WildMenu = { fg = colors.bg, bg = colors.yellow },
  Error = { fg = colors.error },
  Todo = { fg = colors.yellow },
  RedrawDebugClear = { fg = colors.fg, bg = colors.yellow },
  RedrawDebugComposed = { fg = colors.fg, bg = colors.green },
  RedrawDebugRecomposed = { fg = colors.fg, bg = colors.error },

  DiagnosticError = { fg = colors.error },
  DiagnosticWarn = { fg = colors.warning },
  DiagnosticInfo = { fg = colors.white },
  DiagnosticHint = { fg = colors.green },
  DiagnosticUnderlineError = { sp = colors.error, undercurl = true },
  DiagnosticUnderlineWarn = { sp = colors.warning, undercurl = true },
  DiagnosticUnderlineInfo = { sp = colors.white, undercurl = true },
  DiagnosticUnderlineHint = { sp = colors.green, undercurl = true },
  DiagnosticUnderlineVirtualTextError = { sp = colors.error, undercurl = true },
  DiagnosticUnderlineVirtualTextWarn = { sp = colors.warning, undercurl = true },
  DiagnosticUnderlineVirtualTextInfo = { sp = colors.white, undercurl = true },
  DiagnosticUnderlineVirtualTextHint = { sp = colors.green, undercurl = true },
  DiagnosticFloatingError = { link = 'DiagnosticError' },
  DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
  DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
  DiagnosticFloatingHint = { link = 'DiagnosticHint' },
  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticSignWarn = { link = 'DiagnosticWarn' },
  DiagnosticSignInfo = { link = 'DiagnosticInfo' },
  DiagnosticSignHint = { link = 'DiagnosticHint' },

  NvimInternalError = { fg = colors.fg, bg = colors.error, undercurl = true },

  NvimTreeWindowPicker = { fg = colors.fg, bg = colors.yellow },
  NvimTreeIndentMarker = { fg = colors.fg },
  NvimTreeFolderIcon = { fg = colors.fg },

  CmpItemAbbr = { fg = colors.fg },
  CmpItemAbbrMatch = { fg = colors.white, bold = true },
  CmpItemAbbrDeprecated = { fg = colors.gray, strikethrough = true },
  CmpItemMenu = { fg = colors.green },
  CmpItemMatchFuzzy = { fg = colors.white },

  Constant = { fg = colors.green },
  Identifier = { fg = colors.fg },
  Statement = { fg = colors.yellow },
  PreProc = { fg = colors.yellow },
  Type = { fg = colors.yellow },
  Special = { fg = colors.fg },
  Comment = { fg = colors.gray },
  StorageClass = { fg = colors.yellow },

  TSStorageClass = { fg = colors.yellow },
  TSNamespace = { fg = colors.fg },
  TSTypeDefenition = { fg = colors.fg },
  TSConstant = { fg = colors.fg },
  TSTypeQualifier = { fg = colors.fg },
  TSTitle = { fg = colors.fg },
  TSFuncMacro = { fg = colors.fg },
  TSType = { fg = colors.fg },

  rustModPath = { fg = colors.fg },
  rustAssert = { fg = colors.fg },
  rustType = { fg = colors.fg },
  rustIndetifier = { fg = colors.fg },
  rustSelf = { fg = colors.fg, bold = true },

  typescriptIdentifier = { fg = colors.fg, bold = true },
  typescriptOperator = { fg = colors.yellow },
  typescriptVariable = { fg = colors.yellow },
  typescriptDOMFormProp = { fg = colors.fg },
  typescriptPaymentShippingOptionProp = { fg = colors.fg },
  typescriptCall = { fg = colors.fg },

  javaScriptIdentifier = { bold = true },

  cType = { fg = colors.yellow },
  cTSType = { fg = colors.yellow },

  rubyScopeOperator = { fg = colors.yellow },
  rubySuperClassOperator = { fg = colors.yellow },
}

return highlights
